spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blogDB
    username: postgres
    password: ZimaBlue685
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true

security:
  jwt:
    secret-key: "+p2qrOFnSogWqO/p/vFjrKZDkaz+6CMOC7ianV5K+Go="
    expiration: 86400000 #one day

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

logging:
  level:
    org.springframework.security: DEBUG
