spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/blogDB
    username: postgres
    password: ZimaBlue685
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true

  data:
    redis:
      port: 6379
      host: localhost
      password: ZimaBlue685

  kafka:
    bootstrap-servers: localhost:9092

security:
  jwt:
    secret-key: "+p2qrOFnSogWqO/p/vFjrKZDkaz+6CMOC7ianV5K+Go="
    access-expiration: 86400000 #one day
    refresh-expiration: 604800000 #seven days

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.kafka: INFO
